### ISSUE TITLE
[v1.8.0]  TypeError: localForage.getItem is not a function

### ISSUE THREAD

**Issue by ssuess** [localForage/localForage#979]
Since upgrading to 1.8.0, I am getting the following errors:

`TypeError: localForage.getItem is not a function` and `TypeError: localForage.clear is not a function`

Is there something I need to change in my code with this new version?

Reverting to 1.7.4 fixes the issue (and is what I have done for now)

**Comment by bencefr** [comment]
localForage.config is not a function either, had to pin the version back to 1.7.4

**Comment by DominicOcean** [comment]
yeah, I'm having the same issue when importing in Angular as import * as localforage from "localforage".

Here is a workaround I'm using right now: const localForage = require('localforage').default;

**Comment by stefandesu** [comment]
Same issue for me. Too bad this release was published without considering that it (apparently) breaks importing. I'm sure there's still a way of importing it properly (for me, the currently documented way does not work), but nonetheless, a minor release shouldn't cause this issue.

**Comment by oguzhankahyaoglu** [comment]
After releasing 1.8.0, our project got broken. Here is the error log of angular 9 project prod build:
````
"export 'LOCALSTORAGE' (imported as 'localForage') was not found in 'localforage'
````
Downgrading to 1.7.4 fixed the issue.

**Comment by tofumatt** [comment]
Argh, super-sorry about this one, looks like we need more tests for these types of things. I've published 1.8.1 with the ESM change reverted, very sorry about that 😢 

So upgrading to 1.8.1 will do the trick. Really sorry about that; I'm working on better integration tests for a new release but they aren't ready yet. I'll make sure this doesn't happen in the future, but it is fixed for now 👍
